# overlays/prod/kustomization.yaml
namespace: rook-ceph
resources:
  - ../../base

patches:
  - path: rook-ceph-overrides.yaml
    target:
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
